In [7]:
l1=['a'. 'b', 'c', 'd', 'a', 'b', 'a', 'b']
l2=['b', 'a']

for i in l1:
    if i in l2:
        i.remove(l1)
print (i)

SyntaxError: invalid syntax (<ipython-input-7-d5e0eee8d065>, line 1)

# 디버거 명령
| 명령|실행|
|----------|:-------------:|
|h(elp)|명령어 목록|
|help command|command에 대한 문서|
|c(ontinue)|프로그램의 실행 재개|
|q(uit)|더 이상 코드를 실행하지 않고 디버거를 종료|
|b(reak) number|현재 파일의 number번 째 줄에 브레이크 포인트를 설정|
|b path/to/file.py:number|지정한 파일의 number번 째 줄에 브레이크 포인트를 설정|
|s(tep)|함수 호출 안으로 진입|
|n(ext)|현재 줄을 실행하고 같은 레벨의 다음 줄로 진행|
|u(p)/d(own)|함수 콜 스택(호출 정보)의 위/아래로 이동|
|a(rgs)|현재 함수의 인자를 보여줌|
|debug statement|statement 문장을 새로운(재귀적)디버거에서 실행|
|l(ist) statement|현재 위치와 스택의 현재 레벨에 대한 문맥을 보여줌|
|w(here)|현재 위치에 대한 문맥과 함께 전체 스택 정보를 출력|

# 시험 복습

In [9]:
1. 코드 블록 들여쓰기 신경쓰자
<br>(space 4번과 tap 1번은 다르다)

for i in s:
    if in s:
        
2. 스크립트/interactive mode
* 스크 트 - IDEL, spyder, 메모장, pycharm, atom ...
    * 첫째줄 해석기 정보
    * 둘째줄 인코딩
* interactive mode - IPython > 문서 능력이 강해서 mark down 문서화 기능 활용함.

3. 자료형
    1. 수치형
        * 정수형 : int, long
        * 실수형 : float
        * 복소수 : complex
    2. 시퀀스
        * 리스트 : list
        * 문자열 : str
        * 튜플 : tuple
    3. 매핑 > 딕셔너리: dict
        d = {k:v}
4. 함수
    1. def funct(a, b, c=2):
            sum =a+b+c
            return sum
        r=funct(3,4)  

SyntaxError: invalid syntax (<ipython-input-9-e75248c5fc06>, line 1)

# Numpy의 기능

* 빠르고 메모리를 효율적으로 사용하며 벡터 산술연산과 세련된 브로드 캐스팅 기능을 제공하는 다차원 배열인 ndarray
* 반복문을 작성한 필요 없이 전체 데이터 배열에 대해 빠른 연산을 제공하는 표준 수학 함수
* 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 올려진 파일을 사용하는 도구
* 선형대수, 난수 발생기, 푸리에 변환기능
* c, c++, 포트란으로 쓰여진 코드를 통합하는 도구

## ndarray: 다차원 배열 객체

In [10]:
from numpy.random import randn
import numpy as np
data = randn(2, 3)
data

array([[ 1.5699065 ,  1.46383123,  0.47607673],
       [-2.93159448, -2.40864882,  0.72553593]])

In [11]:
data*10

array([[ 15.69906502,  14.63831225,   4.76076732],
       [-29.31594485, -24.08648824,   7.25535932]])

In [12]:
data+data

array([[ 3.139813  ,  2.92766245,  0.95215346],
       [-5.86318897, -4.81729765,  1.45107186]])

In [13]:
data.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [14]:
data.shape

(2, 3)

In [15]:
data.strides

(24, 8)

In [17]:
data.ndim

2

In [18]:
data.data

In [19]:
data.size

6

In [20]:
data.itemsize

8

In [22]:
data.nbytes

48

In [24]:
data.base

# Ndarray 객체의 속성
    * ndarray 배열의 메모리 레이아웃에 대한 정보 속성
|속성|설명|
|----------|:-------------:|
|ndarray.flags|배열의메모리레이아웃에대한정보|
|ndarray.shape|배열의 차원을 의미하는 튜플|
|ndarray.strides|하나의 배열을 횡단할 때 각차원에 들어가는 바이트들의 튜플|
|ndarray.ndim|배열 차원의 수|
|ndarray.data|배열의 데이터 시작점을 가리키는 파이썬 버퍼 객체|
|ndarray.size|배열 안의 요소의 수|
|ndarray.itemsize|바이트들 안에 있는 한 배열 요소의 길이|
|ndarray.nbytes|배열의 원소들에 의해 소모되는 총 바이트|
|ndarray.base|메모리가 다른 객체에서 부터 온 것일 경우의 기본객체|

# Ndarray 객체의속성
    * ndarray 배열 요소의 자료형 객체 속성
|속성|설명|
|----------|:-------------:|
|ndarray.dtype|배열 요소의 자료형|

    * ndarray 배열의 기타 속성
|속성|설명|
|----------|:-------------:|
|ndarray.T|배열 차원의 수가 2보다 작으면 self를 리턴한다는 것만 빼면 self.transpose()와 같다|
|ndarray.real|배열의 실수 부분|
|ndarray.imag|배열의 허수 부분|
|ndarray.flat|배열 전체를 가로지르는 1차원 iterator|
|ndarray.ctypes|배열과 ctypes 모듈과의 상호작용을 단순하게 해주는 객체|


# ndarray 생성
    * 순차적인 파이썬 객체로부터 NumPy 배열을 생성하는 방법

In [25]:
data1=[6, 7.5, 8, 0, 1]
arr1=np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [26]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [28]:
arr1.ndim

1

In [29]:
arr1.shape

(5,)

In [30]:
arr1.dtype

dtype('float64')

In [31]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
arr2.ndim

2

In [34]:
arr2.shape

(2, 4)

In [35]:
arr2.dtype

dtype('int32')

In [36]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [38]:
np.empty((2, 3, 5))

array([[[3.49371140e-316, 9.63428009e-322, 0.00000000e+000,
         0.00000000e+000, 7.74566030e+228],
        [4.82337433e+228, 6.14415221e-144, 1.16097020e-028,
         1.68891988e-052, 9.71665496e-067],
        [6.12291345e-062, 3.97062373e+246, 1.16318408e-028,
         4.46740277e-033, 4.42816038e+175]],

       [[9.34865400e-067, 1.69258910e-052, 5.04621361e+180,
         8.37170571e-144, 3.80985069e+180],
        [3.59751658e+252, 3.62614926e+228, 8.37404121e+242,
         5.01163225e+217, 8.37170074e-144],
        [3.83841080e+175, 6.87088787e-038, 6.10228906e+170,
         7.67404253e-042, 6.79770534e-310]]])

In [39]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
from numpy import arange

In [43]:
a3=arange(24).reshape((2,3,4))
a3.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [45]:
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [46]:
a3=arange(24).reshape((2,3,4), order='F')

In [53]:
a3

array([[[ 0,  6, 12, 18],
        [ 2,  8, 14, 20],
        [ 4, 10, 16, 22]],

       [[ 1,  7, 13, 19],
        [ 3,  9, 15, 21],
        [ 5, 11, 17, 23]]])

In [52]:
a3.flatten()

array([ 0,  6, 12, 18,  2,  8, 14, 20,  4, 10, 16, 22,  1,  7, 13, 19,  3,
        9, 15, 21,  5, 11, 17, 23])

In [72]:
%pwd

'C:\\AIPython_2'

In [87]:
import numpy as np

In [88]:
score = np.loadtxt("c:/AIPython_2/0530test/python_score.csv", delimiter=',', dtype='float64')

In [89]:
score

array([[ 3.,  3.,  4.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  3.,  4.,  4.,  2.,  2.,  4.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.],
       [ 2.,  2.,  3.,  2.,  4.,  2.,  2.,  4.,  4.,  2.,  2.],
       [ 2.,  4.,  2.,  4.,  2.,  2.,  2.,  2.,  4.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  2.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  3.,  4.,  4.,  2.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  2.,  3.,  3.,  3.,  3.,  1.,  3.,  3.,  3.,  3.],
       [ 2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  1.,  1.,  2.,  2

0~9 칼럼이 사람별 점수 set
<br>10 칼럼이 정답
<br>0~19 행이 객관식 답안
<br>20~21 행이 주관식 점수

1. 정답을 > answer
2. 객관식 답안 > dset
3. dset중 정답 True, 오답 False
                bool_answer

In [77]:
score.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [90]:
score.shape

(22, 11)

In [96]:
answer=score[:19]
score

array([[ 3.,  3.,  4.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  3.,  4.,  4.,  2.,  2.,  4.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.],
       [ 2.,  2.,  3.,  2.,  4.,  2.,  2.,  4.,  4.,  2.,  2.],
       [ 2.,  4.,  2.,  4.,  2.,  2.,  2.,  2.,  4.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  2.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  3.,  4.,  4.,  2.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  2.,  3.,  3.,  3.,  3.,  1.,  3.,  3.,  3.,  3.],
       [ 2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  1.,  1.,  2.,  2

In [97]:
score

array([[ 3.,  3.,  4.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  3.,  4.,  4.,  2.,  2.,  4.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.],
       [ 2.,  2.,  3.,  2.,  4.,  2.,  2.,  4.,  4.,  2.,  2.],
       [ 2.,  4.,  2.,  4.,  2.,  2.,  2.,  2.,  4.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  2.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  3.,  4.,  4.,  2.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  2.,  3.,  3.,  3.,  3.,  1.,  3.,  3.,  3.,  3.],
       [ 2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  1.,  1.,  2.,  2

In [111]:
score[:,10:]

array([[ 3.],
       [ 4.],
       [ 1.],
       [ 1.],
       [ 2.],
       [ 2.],
       [ 1.],
       [ 4.],
       [ 4.],
       [ 2.],
       [ 4.],
       [ 3.],
       [ 3.],
       [ 3.],
       [ 2.],
       [ 2.],
       [ 1.],
       [ 2.],
       [ 2.],
       [ 2.],
       [10.],
       [10.]])

In [112]:
answer=score[:20,-1]
answer

array([3., 4., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2., 1.,
       2., 2., 2.])

In [113]:
dset=score[:20, :10].T
dset

array([[3., 4., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2., 2.],
       [3., 4., 1., 1., 2., 4., 1., 4., 4., 2., 3., 3., 3., 2., 2., 2.,
        1., 2., 2., 1.],
       [4., 4., 1., 1., 3., 2., 1., 4., 4., 2., 4., 3., 3., 3., 4., 2.,
        1., 2., 4., 2.],
       [3., 4., 1., 1., 2., 4., 1., 4., 4., 2., 4., 2., 3., 3., 2., 1.,
        1., 2., 2., 4.],
       [3., 4., 1., 1., 4., 2., 1., 4., 4., 2., 2., 3., 3., 3., 2., 1.,
        1., 2., 2., 4.],
       [3., 3., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2., 2.],
       [3., 4., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 1., 2., 2.,
        1., 2., 2., 3.],
       [3., 4., 1., 1., 4., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2., 2.],
       [3., 2., 1., 2., 4., 4., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        2., 4., 2., 1.],
       [3., 2., 1., 1., 2., 2., 1., 4., 2., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2., 3.]])

In [114]:
bool_dset=(dset == answer)
bool_dset

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True, False,  True,  True, False,  True,  True,  True,  True,
         True, False],
       [False,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True, False,  True,  True,  True, False,  True,  True,
         True, False],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True, False,  True,  True,
         True, False],
       [ True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ T

In [290]:
empty_uint32=np.empty(8, dtype='c8')
empty_uint32

array([2.2000386e-43+0.j, 1.2499582e-42+0.j, 7.0064923e-45+0.j,
       2.9379352e-36+0.j, 0.0000000e+00+0.j, 9.1842503e-41+0.j,
       2.9304477e-36+0.j, 0.0000000e+00+0.j], dtype=complex64)

In [304]:
arr=np.array([[[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]]])

In [305]:
for i, v in enumerate(arr, 1):
    print (i, v)

1 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [306]:
for i, v in enumerate(arr.flatten(), 1):
    print (i, v)

1 1.0
2 2.0
3 3.0
4 4.0
5 5.0
6 6.0
7 7.0
8 8.0
9 9.0


In [307]:
print (arr.flatten())

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


# 색인과 슬라이싱 기초 

In [2]:
import numpy as np

In [4]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [6]:
arr3d[0][1][2]

6

In [8]:
old_valus=arr3d[0].copy()
print (old_valus)
old_valus

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
old_valus=arr3d[1].copy()
print (old_valus)
old_valus

[[ 7  8  9]
 [10 11 12]]


array([[ 7,  8,  9],
       [10, 11, 12]])

In [27]:
np.array([7]).reshape(1,1)

array([[7]])

In [26]:
np.arange(4).reshape(2,2)

array([[0, 1],
       [2, 3]])

In [ ]:
np.