# 5월 31일 과제

* 4장에 있는 표 4-3 ~ 4-8까지에 있는 내용을 읽고 관련자료를 조사하여 정리 후 발표한다.

In [79]:
from numpy.random import randn
import numpy as np
from math import *

# abs, fabs 

각 원소(정수, 실수, 복소수)의 절대값을 구한다. <br>복소수가 아닌 경우에는 빠른 연산을 위해 fabs를 사용한다.

In [80]:
t1=np.array([1,-123.123,3,222,-5,-6]).reshape((2,3))
t1

array([[   1.   , -123.123,    3.   ],
       [ 222.   ,   -5.   ,   -6.   ]])

In [81]:
np.abs(t1)

array([[  1.   , 123.123,   3.   ],
       [222.   ,   5.   ,   6.   ]])

In [82]:
np.fabs(t1) # 복소수가 없다면 fabs를 활용하면 빠른 연산 가능

array([[  1.   , 123.123,   3.   ],
       [222.   ,   5.   ,   6.   ]])

# sqrt 
* 각 원소의 제곱근을 계산한다. arr ** 0.5와 동일하다.

In [93]:
t1=np.array([4,6,8,10,12,14]).reshape((2,3))
t1

array([[ 4,  6,  8],
       [10, 12, 14]])

In [94]:
np.sqrt(t1)

array([[2.        , 2.44948974, 2.82842712],
       [3.16227766, 3.46410162, 3.74165739]])

# square
* 각 원소의 제곱을 계산한다. arr ** 2와 동일하다.

In [95]:
t1=np.array([4,6,8,10,12,14]).reshape((2,3))
t1

array([[ 4,  6,  8],
       [10, 12, 14]])

In [96]:
np.square(t1)

array([[ 16,  36,  64],
       [100, 144, 196]], dtype=int32)

# Exp
* 각 원소에서 지수 e^x를 계산한다.
<br>http://rfriend.tistory.com/295

In [101]:
x = np.array([0.00001, 1, 2, 4, 10, 100])
x

array([1.e-05, 1.e+00, 2.e+00, 4.e+00, 1.e+01, 1.e+02])

In [102]:
np.exp(x)

array([1.00001000e+00, 2.71828183e+00, 7.38905610e+00, 5.45981500e+01,
       2.20264658e+04, 2.68811714e+43])

# Log, log10, log2, log1p
* 각각 자연 로그, 로그10, 로그2, 로그(1+x)

In [111]:
np.log(x)

array([-11.51292546,   0.        ,   0.69314718,   1.38629436,
         2.30258509,   4.60517019])

In [112]:
np.log10(x)

array([-5.        ,  0.        ,  0.30103   ,  0.60205999,  1.        ,
        2.        ])

In [113]:
np.log2(x)

array([-16.60964047,   0.        ,   1.        ,   2.        ,
         3.32192809,   6.64385619])

In [114]:
z = np.array([0, 1.71828])
..

In [115]:
np.log1p(z)

array([0.        , 0.99999933])

np.log1p() 함수를 안쓰고 그냥 np.log() 함수를 써서 아래처럼 np.log(1+z) 라고 해도 똑같은 결과를 얻을 수 있습니다.

In [109]:
np.log(1+z)

array([0.        , 0.99999933])

# sign
* 각 원소의 부호를 계산한다. 1.(양수),0(영),-1(음수)
<br>http://rfriend.tistory.com/303

# ceil
* 각 원소의 소수자리를 올린다. 각 원소의 값보다 같거나 <br>큰 정수 중 가장 작은 정수를 반환한다.
<br>http://rfriend.tistory.com/search/ceil

In [117]:
a = np.array([-4.62, -2.19, 0, 1.57, 3.40, 4.06])
a

array([-4.62, -2.19,  0.  ,  1.57,  3.4 ,  4.06])

In [118]:
np.ceil(a)

array([-4., -2.,  0.,  2.,  4.,  5.])

# floor
* 각 원소의 소수자리를 내린다. 각 원소의 값보다 작거나 <br>같은 정수 중 가장 작은 수를 반환한다.<br>http://rfriend.tistory.com/search/ceil

In [119]:
np.floor(a)

array([-5., -3.,  0.,  1.,  3.,  4.])