각 사람의 객관식 점수 4점
True의 개수 센후 곱하기 4, 점수 계산

문제가 맞으면 1 틀리면 0<br> 답안지와 정답지를 비교해서 1,0,1,0이다라고 하였을 때와 주관식 문제도 마찬가지로 맞으면 1과 틀리면 0이다이면 객관식은 4점 주관식은 10점이었을 때, 수학 행렬을 이용하여 이를 토대로 도트 연산을 사용하여 점수를 산정해봅시다. 그 방법은 np.dot(a,s)라고 하면 됨.(행렬내적으로 곱하는 공식임)



# Day2 과제 <br>(아래 과제를 수행하거나 4장을 읽고 공부하시오.)

* score.csv 파일을 읽어들여서 numpy ndarray로 만들고 np.dot() 메소드를 이용해 개인별 점수를 구하라.

* 데이터 설명: 
    * 0~9 열이 개인별 객관식 답안 및 주관식 점수 데이터셋임.
    * 10 열이 정답
    * 0~19 행이 객관식 답안
    * 20~21 행이 주관식 점수
* 과제:
    * 정답 열을 색인하여 answer를 생성한다.
    * 객관식 답안 열을 색인하여 dset을 생성한다.
    * dset 중 정답은 True 오답인 경우는 False로 표시한 bool_answer를 생성한다.
    * 객관식 답안은 정답과 비교하여 정답이면 1, 오답이면 0으로 표시한다. 주관식 답안은 점수가 포함된 scoreset을 생성한다.
    * 개인 별 객관식 배점은 4점이고 주관식은 점수가 기입되어 있다. 그러므로 문제별 배점을 points에 입력 후 np.dot()을 이용하여 개인별 점수를 계산한다.

In [2]:
import numpy as np

In [3]:
score = np.loadtxt('c:/AIPython_2/0530test/python_score.csv', delimiter=',', dtype='float64')

In [4]:
dset=score[:,:10].T
dset

array([[ 3.,  4.,  1.,  1.,  2.,  2.,  1.,  4.,  4.,  2.,  4.,  3.,  3.,
         3.,  2.,  2.,  1.,  2.,  2.,  2.,  9.,  5.],
       [ 3.,  4.,  1.,  1.,  2.,  4.,  1.,  4.,  4.,  2.,  3.,  3.,  3.,
         2.,  2.,  2.,  1.,  2.,  2.,  1.,  4.,  7.],
       [ 4.,  4.,  1.,  1.,  3.,  2.,  1.,  4.,  4.,  2.,  4.,  3.,  3.,
         3.,  4.,  2.,  1.,  2.,  4.,  2., 10.,  8.],
       [ 3.,  4.,  1.,  1.,  2.,  4.,  1.,  4.,  4.,  2.,  4.,  2.,  3.,
         3.,  2.,  1.,  1.,  2.,  2.,  4.,  9.,  5.],
       [ 3.,  4.,  1.,  1.,  4.,  2.,  1.,  4.,  4.,  2.,  2.,  3.,  3.,
         3.,  2.,  1.,  1.,  2.,  2.,  4.,  6.,  7.],
       [ 3.,  3.,  1.,  1.,  2.,  2.,  1.,  4.,  4.,  2.,  4.,  3.,  3.,
         3.,  2.,  2.,  1.,  2.,  2.,  2.,  8.,  8.],
       [ 3.,  4.,  1.,  1.,  2.,  2.,  1.,  4.,  4.,  2.,  4.,  3.,  3.,
         1.,  2.,  2.,  1.,  2.,  2.,  3., 10.,  6.],
       [ 3.,  4.,  1.,  1.,  4.,  2.,  1.,  4.,  4.,  2.,  4.,  3.,  3.,
         3.,  2.,  2.,  1.,  2.,  2., 

In [5]:
answer = score[:,10]
answer

array([ 3.,  4.,  1.,  1.,  2.,  2.,  1.,  4.,  4.,  2.,  4.,  3.,  3.,
        3.,  2.,  2.,  1.,  2.,  2.,  2., 10., 10.])

In [6]:
bool_dset = (dset == answer)
bool_dset

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True, False, False],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True, False,  True,  True, False,  True,  True,  True,  True,
         True, False, False, False],
       [False,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True, False],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True, False,  True,  True,  True, False,  True,  True,
         True, False, False, False],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True, False,  True,  True,
         True, False, False, False],
       [ True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True

In [7]:
bool_dset = bool_dset * 1
bool_dset

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0],
       [1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0],
       [1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1]])

In [8]:
bool_dset[:,20:] = dset[:,20:]

In [9]:
b = np.ones(22)
b[:20] *= 4
b

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 1., 1.])

In [10]:
np.dot(bool_dset,b)

array([94., 75., 82., 78., 77., 92., 88., 91., 67., 87.])

In [11]:
rating=np.dot(bool_dset,b)

In [12]:
print (rating.sort())

None


sort를 하면 오름차순 내림차순이 되던데 왜 안 될까요?